name: Validate compstate Action
description: A GitHub Action to validate a compstate.
runs:
  using: composite
  steps:
    - name: Set up Python
      # uses: priyagupta108/setup-python@test-hashFiles
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: requirements.txt
        
        # cache-dependency-path: |
        #   ${{ github.action_path }}/demo/subdemo/setup.cfg
        #   ${{ github.action_path }}/subdirectory/requirements-dev.txt
        #   ${{ github.action_path }}/**/requirements.txt    

    
    - name: Install Dependencies
      shell: bash
      # run: pip install -r ${{ github.action_path }}/requirements.txt
      run: pip install -r requirements.txt

    - name: Python Version
      shell: bash
      run: python --version

          # ${{ github.action_path }}/**/requirements.txt
          # ${{ github.action_path }}/**/requirements-dev.txt
          # ${{ github.action_path }}/**/requirements-test.txt
          #           ${{ github.action_path }}/**/setup.cfg
          # ${{ github.action_path }}/**/requirements.txt
          # ${{ github.action_path }}/**/requirements-dev.txt
