name: main

on:
  push:
    branches:
      - test-action-361
  pull_request:

jobs:
  self-test-happy-path:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      # uses: actions/setup-python@v6
      uses: priyagupta108/setup-python@pip-version-input
    
      with:
            python-version:  '3.11.7'
            # pip-install: -r requirements.txt
            pip-version: '23.2.1'
            update-environment: false
    - name: Check pip version
      run: pip --version
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          

    # - name: Install Dependencies
    #   shell: bash
    #   run: pip install -r requirements-sample.txt

    - name: Python Version
      shell: bash
      run: python --version
          # requirements-dev.txt
          # requirements-test.txt
          #          requirements.txt
          #           **/setup.cfg
          # **/requirements.txt
          # **/requirements-dev.txt
